//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summative_Project___Cash_Register___Dungeon_Merchant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Summative_Project___Cash_Register___Dungeon_Merchant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1000_F_304962032_iKSsf0dcThrZ28GgGkLqqkzVkeGXxMCV {
            get {
                object obj = ResourceManager.GetObject("1000_F_304962032_iKSsf0dcThrZ28GgGkLqqkzVkeGXxMCV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _110618_fire_flames_adobestock_134229099 {
            get {
                object obj = ResourceManager.GetObject("110618-fire-flames-adobestock_134229099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _110618_fire_flames_adobestock_1342290991 {
            get {
                object obj = ResourceManager.GetObject("110618-fire-flames-adobestock_1342290991", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1156704 {
            get {
                object obj = ResourceManager.GetObject("1156704", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _120753_abstract_cool_grey_texture_background_image {
            get {
                object obj = ResourceManager.GetObject("120753-abstract-cool-grey-texture-background-image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _155489_abstract_dark_grey_background {
            get {
                object obj = ResourceManager.GetObject("155489-abstract-dark-grey-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _155500_abstract_dark_grey_background_design {
            get {
                object obj = ResourceManager.GetObject("155500-abstract-dark-grey-background-design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_264076292_eajc66GtVUHIkF9tl8y3vUPgJMSfVKy0 {
            get {
                object obj = ResourceManager.GetObject("360_F_264076292_eajc66GtVUHIkF9tl8y3vUPgJMSfVKy0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_264086703_lXyO66qXXB3q8K6aJMFUyMMbWCowGBEr {
            get {
                object obj = ResourceManager.GetObject("360_F_264086703_lXyO66qXXB3q8K6aJMFUyMMbWCowGBEr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4fb1980f2c282048035630fe60fcab74_t {
            get {
                object obj = ResourceManager.GetObject("4fb1980f2c282048035630fe60fcab74_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4fb1980f2c282048035630fe60fcab74_t__1_ {
            get {
                object obj = ResourceManager.GetObject("4fb1980f2c282048035630fe60fcab74_t (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4fb1980f2c282048035630fe60fcab74_t__1___1_ {
            get {
                object obj = ResourceManager.GetObject("4fb1980f2c282048035630fe60fcab74_t (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_geometric_background_black_and_white_vector_10383012 {
            get {
                object obj = ResourceManager.GetObject("abstract-geometric-background-black-and-white-vector-10383012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dark_grey_background_phpf8ys7h4fgijgt {
            get {
                object obj = ResourceManager.GetObject("dark-grey-background-phpf8ys7h4fgijgt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dark_grey_background_phpf8ys7h4fgijgt1 {
            get {
                object obj = ResourceManager.GetObject("dark-grey-background-phpf8ys7h4fgijgt1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dungeon {
            get {
                object obj = ResourceManager.GetObject("Dungeon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edd9fee3f8b01c63c34fd9e7e0e21ea7 {
            get {
                object obj = ResourceManager.GetObject("edd9fee3f8b01c63c34fd9e7e0e21ea7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edd9fee3f8b01c63c34fd9e7e0e21ea71 {
            get {
                object obj = ResourceManager.GetObject("edd9fee3f8b01c63c34fd9e7e0e21ea71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edd9fee3f8b01c63c34fd9e7e0e21ea72 {
            get {
                object obj = ResourceManager.GetObject("edd9fee3f8b01c63c34fd9e7e0e21ea72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f984087c4acbf38e9d1bdb95722b83db {
            get {
                object obj = ResourceManager.GetObject("f984087c4acbf38e9d1bdb95722b83db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_113494458_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-113494458-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_che_guevara_png_1164718 {
            get {
                object obj = ResourceManager.GetObject("NicePng_che-guevara-png_1164718", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_che_guevara_png_1164718__1_ {
            get {
                object obj = ResourceManager.GetObject("NicePng_che-guevara-png_1164718 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cool_blue_crystal_triangle_background_image_708168 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cool-blue-crystal-triangle-background-image_708168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream receiptPrinter {
            get {
                return ResourceManager.GetStream("receiptPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap receiptSoundEffect {
            get {
                object obj = ResourceManager.GetObject("receiptSoundEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream receiptSoundEffect1 {
            get {
                return ResourceManager.GetStream("receiptSoundEffect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_merchant {
            get {
                object obj = ResourceManager.GetObject("rsz_merchant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_nicepng_che_guevara_png_1164718 {
            get {
                object obj = ResourceManager.GetObject("rsz_nicepng_che-guevara-png_1164718", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_nicepng_che_guevara_png_1164718__1_ {
            get {
                object obj = ResourceManager.GetObject("rsz_nicepng_che-guevara-png_1164718 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap static_dark_grey_design {
            get {
                object obj = ResourceManager.GetObject("static-dark-grey-design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_design_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("Untitled_design-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_design_removebg_preview__1___1_ {
            get {
                object obj = ResourceManager.GetObject("Untitled_design-removebg-preview (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_design_removebg_preview__2_ {
            get {
                object obj = ResourceManager.GetObject("Untitled_design-removebg-preview (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_design_removebg_preview__2_1 {
            get {
                object obj = ResourceManager.GetObject("Untitled_design-removebg-preview (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
